### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by Loponka13** [IN21Dev/AutonomerRoboter#6]
Es müssen Methoden zur Bewegung Vorwärts / Rückwärts und Navigation nach links und rechts

**Comment by CR4Wz** [comment]
Erste Recherche: [QUELLE](https://docs.arduino.cc/retired/archived-

CompassRead eventuell möglich, um die Lokalisierung der Pakete zu vereinfachen (?)

**compassRead()**
**Description**
Get the current direction from on-board compass. The values are degrees of rotation from north (in a clockwise direction), so that east is 90, south is 180, and west is 270.

**Syntax**
`Robot.compassRead()`

**Parameters**
none

**Returns**
int: 0 to 359, representing the number of degrees of rotation from north.

**Note**
The compass module may be disrupted by magnetic fields in surrounding areas.

Examples
`#include <ArduinoRobot.h>

void setup(){
  Robot.begin();
  Serial.begin(9600);

}
void loop(){
  Serial.println(Robot.compassRead());
  delay(100);
}`

**keyboardRead()**

**Description**
Detects if one of the 5 momentary buttons on the control board is pressed.

**Syntax**
`Robot.keyboardRead()`

**Parameters**
none

Returns

- BUTTON_NONE if no key is pressed
- BUTTON_LEFT if left key is pressed
- BUTTON_DOWN if down key is pressed
- BUTTON_UP if up key is pressed
- BUTTON_RIGHT if right key is pressed
- BUTTON_MIDDLE if middle key is pressed

**Examples**
```
#include <ArduinoRobot.h>

void setup(){
  Robot.begin();
  Serial.begin(9600);
}

void loop(){
  Serial.println(Robot.keyboardRead());
  delay(100);
}

```
